### ISSUE TITLE
Please publish a feature for installation in Eclipse

### ISSUE THREAD

**Issue by stephan-herrmann** [kdvolder/lsp4e#2]
I'm coming from eclipse/wildwebdeveloper#84 and would like to test the fix in ServerMessageHandler.java, but the provided update site cannot be used interactively, because it contains no feature for installation.

Could you please add a simple feature?

**Comment by kdvolder** [comment]
Did you mean to raise this issue against the Eclipse lsp4e project? This is just a personal clone of the project that I have created to make an occasional PR agains their code.

Bugzilla link: https://bugs.eclipse.org/bugs/enter_bug.cgi?product=LSP4E&component=General

**Comment by stephan-herrmann** [comment]
sorry Kris, I was misled by github linking a fix for eclipse/wildwebdeveloper#84 back to this repo, not bugzilla.

**Comment by kdvolder** [comment]
NP :-)
